"""
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
"""

from math import sqrt

def count_factors(num):
    if num == 0:
        return 0
    if num == 1:
        return 1

    factors = 2 # 1 and itself
    for x in range(2, int(sqrt(num)) + 1):
        if num % x == 0:
            factors = factors + 2
    if int(sqrt(num)) * int(sqrt(num)) == num:
        factors = factors - 1
    return factors

triangle = 0
next_number = 1

while count_factors(triangle) <= 500:
    triangle = triangle + next_number
    next_number = next_number + 1

print(triangle)

